name: Build Kepler.GL & publish to GitHub packages

on: push

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 12
  #     - uses: actions/checkout@v2
  #     - uses: borales/actions-yarn@v3.0.0
  #       with:
  #         cmd: install # will run `yarn install` command
  #     - uses: borales/actions-yarn@v3.0.0
  #       with:
  #         cmd: build # will run `yarn build` command

  publish-gpr:
    # needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2.1.1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install -g yarn
      - run: yarn
      - run: npm publishs
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
