name: Build Kepler.GL & publish to GitHub packages

on: push

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          # registry-url: https://registry.npmjs.org/
          registry-url: https://npm.pkg.github.com
      - run: npm install -g yarn
      - run: yarn
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
